default:
  theme_advanced_toolbar_location: top
  theme_advanced_toolbar_align: left
  theme_advanced_statusbar_location: none
  theme_advanced_buttons3_add:
    - tablecontrols
    - fullscreen
  plugins:
    - table
    - fullscreen
  style_formats:
    - title: 'Bold text'
      inline: 'b'
    - title: 'Red text'
      inline: 'span'
      styles:
        color : '#ff0000'
  file_browser_callback: 'file_upload'
